<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>_3_LibraryServices</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>false</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\1_LibraryClasses\1_LibraryClasses.csproj" />
    <ProjectReference Include="..\2_LibraryUtils\2_LibraryUtils.csproj" />
  </ItemGroup>

</Project>